import { CircleAlert, CircleCheck, FlaskConical, Info, OctagonAlert, Radio, TriangleAlert, Beaker } from "lucide-react";

import { cn } from "@/lib/utils";
import type { Severity, SourceType } from "@/types/api";

// Severity is status, not identity: the fixed status palette, always with an
// icon and the word, never color alone. MEDIUM (warning) and HIGH (serious)
// fail the normal-vision separation floor as bare colors, so the icon and
// label carry the distinction.
const SEVERITY_STYLE: Record<Severity, { icon: typeof Info; color: string; label: string }> = {
  SAFE: { icon: CircleCheck, color: "var(--status-good)", label: "Safe" },
  LOW: { icon: Info, color: "var(--status-low)", label: "Low" },
  MEDIUM: { icon: CircleAlert, color: "var(--status-warning)", label: "Medium" },
  HIGH: { icon: TriangleAlert, color: "var(--status-serious)", label: "High" },
  CRITICAL: { icon: OctagonAlert, color: "var(--status-critical)", label: "Critical" },
};

export function SeverityBadge({ severity, className }: { severity: Severity; className?: string }) {
  const style = SEVERITY_STYLE[severity];
  const Icon = style.icon;
  return (
    <span
      className={cn(
        "inline-flex h-5 items-center gap-1 rounded-full border px-2 text-xs font-medium whitespace-nowrap text-foreground",
        className,
      )}
      style={{
        borderColor: `color-mix(in oklab, ${style.color} 45%, transparent)`,
        backgroundColor: `color-mix(in oklab, ${style.color} 14%, transparent)`,
      }}
    >
      <Icon className="size-3" style={{ color: style.color }} aria-hidden />
      {style.label}
    </span>
  );
}

// Brief §26: LIVE, SIMULATED and DEMO_DATA must never be confused. Each has
// its own icon and wording; none of them borrows a status color.
const SOURCE_STYLE: Record<SourceType, { icon: typeof Info; label: string; title: string }> = {
  LIVE: { icon: Radio, label: "Live", title: "Real data from an integration or a user upload" },
  SIMULATED: { icon: FlaskConical, label: "Simulated", title: "Activity generated by Sentivra's endpoint simulator" },
  DEMO_DATA: { icon: Beaker, label: "Demo data", title: "Bundled synthetic sample data" },
};

export function SourceTypeBadge({ sourceType, className }: { sourceType: SourceType | null; className?: string }) {
  if (!sourceType) {
    return <span className={cn("text-xs text-muted-foreground", className)}>Unknown source</span>;
  }
  const style = SOURCE_STYLE[sourceType];
  const Icon = style.icon;
  return (
    <span
      title={style.title}
      className={cn(
        "inline-flex h-5 items-center gap-1 rounded-md border px-1.5 text-xs font-medium whitespace-nowrap",
        sourceType === "LIVE" ? "border-foreground/25 text-foreground" : "border-dashed border-foreground/30 text-muted-foreground",
        className,
      )}
    >
      <Icon className="size-3" aria-hidden />
      {style.label}
    </span>
  );
}

type Availability = "Available" | "Not Configured" | "Not configured" | "Degraded" | "Error" | "Not implemented" | "Connected";

export function StatusPill({ status }: { status: Availability | string }) {
  const good = status === "Available" || status === "Connected";
  const partial = status === "Degraded";
  const bad = status === "Error";
  const color = good ? "var(--status-good)" : partial ? "var(--status-warning)" : bad ? "var(--status-critical)" : "var(--status-low)";
  const Icon = good ? CircleCheck : partial ? TriangleAlert : bad ? OctagonAlert : Info;
  return (
    <span className="inline-flex items-center gap-1 text-xs font-medium whitespace-nowrap text-foreground">
      <Icon className="size-3.5" style={{ color }} aria-hidden />
      {status}
    </span>
  );
}
